' PlantUML file for the Activity Diagram in POOSD Assignment #3 with Dr. Aashish Yadavally
' Code written by Adam Betinsky on Saturday, March 21st, 2026

' START OF "activity.puml"
@startuml

' Add start node as the user must want to visit the site
start

' Add flow for loading the site
:Go To The Website on The Internet (www.betinsky-colorslab.com);
:View Home Page (index.html);

' While loop for staying active on the website (AKA not being done)
while (Leave The Website?) is (No)

    ' Flow for inital login attempt
    :Enter Account Credentials
    (Username and Password) to login;
    :Validate Login;

    ' While loop while attempting to login
    while (Login Valid?) is (No)

        ' Flow for bad login and re-attempting
        :Show Login Error Message;
        :Re-enter Account Credentials
        (Username and Password) to Re-Attempt Login;

    endwhile (Yes)

    ' Flow for when there is a successful login
    :View Main Page (color.html);

    ' While loop for staying logged into your account
    while (Logout of Account?) is (No)

        ' Flow for staying logged into your account
        :Choose An Action;

        ' Flow for adding a color to the database
        if(Add a Color?) then (Yes)
            :Enter New Color;
            :Add Inputted Color Into Database;
            :Show Confirmation Message;

        ' Flow for searching a color to the database (note there is a bunch of spacing on line 48 so the "No" keyword stays closer to the middle of the link)
        (No                                                                                                           ) elseif (Search For a Color?) then (Yes)
            :Enter Color to Search;
            :Query Database for Inputted Color (Including Partial Matches);
            :Display Any Color(s) Found;

            ' Flow for the else case - the user must want to leave the website while still being logged in. Doing this will log them out behind the scenes, so stop here
        else (No)
            :Leave The Website;
            stop

        endif

    endwhile (Yes)

endWhile (Yes)

' The user must want to leave the website, so stop here as well
stop

' Add footer to the diagram
footer Activity Diagram for POOSD Assignment 3 - Adam Betinsky
skinparam footerFontColor black

@enduml
' END OF "activity.puml"