name: POOSD Assignment 4 Linting Workflow

on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repoistory
              uses: actions/checkout@v4
